### ISSUE TITLE
Not working for redmine 3.0

### ISSUE THREAD

**Issue by abcfy2** [jongha/redmine_sticky_messages#6]
When I upgrade my redmine from 2.6 to 3.0, this plugin crashed.

```
Started GET "/redmine" for 106.36.219.240 at 2015-02-23 21:27:45 +0800
Processing by WelcomeController#index as HTML
  Current user: fengyu (id=3)
  Rendered news/_news.html.erb (11.3ms)
  Rendered welcome/index.html.erb within layouts/base (25.1ms)
  Rendered plugins/redmine_sticky_messages/app/views/messages/_after_top_menu.html.erb (4.6ms)
Completed 500 Internal Server Error in 117ms

ActiveRecord::RecordNotFound (Couldn't find all News with 'id': (all, {:limit=>2, :order=>"created_on desc", :include=>[:author]}) (found 0 results, but was looking for 2)):
  lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in `map'
  lib/redmine/hook.rb:117:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
  app/views/layouts/base.html.erb:75:in `_app_views_layouts_base_html_erb___3805841102600204940_33119960'
```

I have downloaded the latest version.

**Comment by jongha** [comment]
Fixed. Thanks. :)

**Comment by shivareddy547** [comment]
I downloaded the latest version(3.0.1) but still i am facing same issue,Please let me know if you find solution.

Thanks
Shiva.A
